// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
    apiKey: "AIzaSyCzc-_AoL853qeCkJv3OvcERFDZ6fCj0nQ",
    authDomain: "clone-d947b.firebaseapp.com",
    projectId: "clone-d947b",
    storageBucket: "clone-d947b.appspot.com",
    messagingSenderId: "340340322962",
    appId: "1:340340322962:web:374bf638b8c682a8ecec4b",
    measurementId: "G-V0G0CVHMV1"
  };